### PR TITLE
CI/CD all the things

### PR DESCRIPTION
**Pull request by thebeanogamer**

### CODE REVIEW

**Review by lightspeedana — APPROVED** [review]

**Comment by picapi** [comment]
If I'm not mistaken it looked like this didn't work properly?

**Comment by lightspeedana** [comment]
Would you like me to merge? It's throwing up an error

**Comment by lightspeedana** [comment]
image

**Comment by thebeanogamer** [comment]
> 
> 
> Would you like me to merge? It's throwing up an error

Most people would not approve it if it's erroring...

**Comment by thebeanogamer** [comment]
Eyes

**Comment by thebeanogamer** [comment]
The uses thereof

**Comment by 0xAda** [comment]
why

**Comment by thebeanogamer** [comment]
> 
> 
> why

Yes

**Comment by lightspeedana** [comment]
> why

I ask myself this every day I spend on this server @david-cooke

**Comment by NicholasG04** [comment]
worst creation ever

**Pull request merged**
