### PR TITLE
Rework Server Rules

### LINKED ISSUE #312: The whole server is a dictatorship and everything I do that is slightly out of line gets deleted or censored.
# Stop the Censorship, let the server be free.

### *A description of the issue:*
My past few issues were jokes however I am trying to convey an issue which has been bugging me and 60 other people in the scrabble server. I know this has been said before but maybe its time to listen.

### *Proposed Solution:*
Loosen up the server a little bit, set rules for mods on what they can and can't delete rather than making it a free for all. Mods seem to delete anything they personally dislike

### *Additional Comments:*
I would like to say that if the mods want to do nothing about this then feel free to close this issue, but it further damages how the mod team is portrayed, I have nothing against the mods personally but I just think that the server could be made better if it wasn't such a dictatorship power struggle.

Edit:
This is almost a continuation of #299 basically everyone except the mods agree.

### PR DESCRIPTION
**Pull request by thebeanogamer**
This is an open consultation on updates to the Server Rules, on which we would appreciate feedback.

Whilst Discord feedback will be accepted, GitHub feedback is far easier to track, so we'd prefer it here if possible.

This pull request will not be merged until we feel that all appropriate feedback has been enacted, and the old rules remain in place until this PR is merged.

Resolves #312

### CODE REVIEW

**Comment by thebeanogamer** [comment]
Also, Dyno has not had the invite exceptions added yet, so don't get annoyed if it deletes them.

**Comment by ghost** [comment]
not bad

**Comment by benabrahamson** [comment]
Looks like there's an error on line 54 of RULES.md.
[https://discord.cyberdiscommunity.uk](https://discord.cyberdiscommunity.uk) is not a valid URL.
Should be [https://discord.cyberdiscoverycommunity.uk](https://discord.cyberdiscoverycommunity.uk)

**Comment by Little-Green-Guy** [comment]
seems pretty good.
some of the punishments seem a bit extreme to me but thats the mods decision to make and at least theyre now documented.

**Review by SSAFuze — APPROVED** [review]

**Comment by lightspeedana** [comment]
@Little-Green-Guy what changes would you propose?

**Comment by R0w4nS** [comment]
Another typo on line 57.
Should be [https://discord.gg/python](url)
not [https://discord/python](url)

**Comment by Little-Green-Guy** [comment]
@lightspeedana none really. straight from a warning to a 1hr mute seems a bit extreme, but it is after a warning, and no doubt there would be a reminder that a 1hr mute is next so its kinda fair
also as to the harassment point, as sometimes people may not realise what they are doing counts as harassment, a straight up 14 day ban (or even permanent) seems extreme. maybe a few hour/day mute first to establish that it isnt allowed, then a temp ban as soon as it is repeated.

**Comment by R0w4nS** [comment]
Already said this in discord, but it would be nice to see some clarity on whether the punishment length is decided by the severity of the action or by if they have already been punished for the same action.

**Review by Sh3llcod3 — APPROVED** [review]
I think it looks ok, I haven't found any glaring issues. Definitely worth taking some steps to increase engagement overall, but that's a separate thing yet to come later. Also, this probably needs to be converted to JSON format for the bot, if this is accepted :+1:

**Comment by NicholasG04** [comment]
uh why is there a mention of sexual harassment in this? Think that's a police issue, not a 14-day ban issue

**Comment by Little-Green-Guy** [comment]
Actually, although it may not need to be included specifically in the rules, can there be some clarification on copypastas?
Of course when copypastas are sent multiple times its spam and should be removed and treated as such, however if its only sent once, its not spam, and I was under the impression it didn't break the rules, and imo it shouldn't be removed. Could this be clarified, one way or the other?

**Comment by Bentechy66** [comment]
This is pretty rad and an awesome step in the right direction. Perhaps, an example of what is and is not acceptable would be useful - also, clarification on what's allowed in overflow, memes, etc.

**Comment by jb3** [comment]
Hello Mr Gamer.

What constitutes as spam? The rules should flesh out a lot more to prevent moderators classing incorrect exhibits of freedom of speech as a violation of the community rules. 

Thank you

**Comment by Bottersnike** [comment]
I disagree on defining terms like `spam`. As soon as a definition is put in place by the rules, people will do the next closest thing, and by the rules it won't be "spam".

**Pull request merged**
