### PR TITLE
Can we remove #linguistics yet?

### PR DESCRIPTION
**Pull request by teamshortcut**
Please?

But in all seriousness; the channel was created for April Fool's day. It was great that it was used for a while afterwards, but it is now inactive and not seriously used, so I think it has run its course.

### CODE REVIEW

**Review by thebeanogamer — APPROVED** [review]
Methinks so

image

**Comment by NicholasG04** [comment]
yespls

**Comment by ghost** [comment]
Remove it

**Comment by maishams** [comment]
can it get archived to remember it

**Comment by thebeanogamer** [comment]
I mean, we can put it in tumbleweed, but you can't see that.

**Comment by ghost** [comment]
Just bin it and add #politics

**Comment by maishams** [comment]
no i mean #the-archive

**Comment by lightspeedana** [comment]
I say it gets archived, it's dead now.

**Review by lightspeedana — APPROVED** [review]

**Comment by thebeanogamer** [comment]
Voting on server setup, give it a couple of days, but I don't expect the result to be ambiguous.

**Comment by thebeanogamer** [comment]
image

**Pull request merged**
