### PR TITLE
On Nate's behalf; #AnaForRoot

### PR DESCRIPTION
**Pull request by teamshortcut**
Because @NateKomodo has said he cannot be bothered to do this, a PR for his suggestion (resolves issue #201) to promote @lightspeedana to Root.

### CODE REVIEW

**Comment by BoatiestBoat** [comment]
This is objectively right

**Comment by NateKomodo** [comment]
The only thing shorty has ever said that I agree with

**Comment by NicholasG04** [comment]
@NateKomodo literally this

**Review by NicholasG04 — APPROVED** [review]
Ana for root

**Comment by NateKomodo** [comment]
Clearly the roots are against us on this one. They are too busy to care about us working class. Join me as I lead the socialist revolution to spear head ana into root and establish socialism. Karl Marx I will make you proud.

**Review by NateKomodo — APPROVED** [review]

**Comment by NicholasG04** [comment]
As a member of the Labour Party I too would like to join you in starting a socialist revolution.

**Comment by NateKomodo** [comment]
Welcome to the revolution, brother.

**Comment by TheFlash787** [comment]
As a tourey, I choose to reject anything that I do not know about. There's my decision.

**Comment by thebeanogamer** [comment]
🤔 
image

**Comment by thebeanogamer** [comment]
🤔 
image

**Comment by NicholasG04** [comment]
@CyberDiscovery/server-admin-team Please can we get this to be merged as soon as possible so that we can bestow Ana in her rightful position and then proceed with issue #207.

Regards,
Nick.
Cyber Discovery Community Labour Party

**Review by thebeanogamer — APPROVED** [review]
This has support from the admin team, and provided that it is voted in favour of, we'd be happy to implement it.

**Comment by lightspeedana** [comment]
To clarify, if there is a majority in favour of me becoming root, I would be more than happy to fill the role and do so.

**Review by lightspeedana — APPROVED** [review]

**Pull request merged**
