### PR TITLE
Add Announcements role

### LINKED ISSUE #280: Ping for Announcements
# Title Of Issue
Make a role for Announcement pinging
### *A description of the issue:*
I have recently missed several announcements as I have been inactive a bit. I feel like in the #readme channel at the bottom there should be a reaction where if you react you get a special role which whenever admins make an announcement they can ping the announcements role to let the people notified without the mess of @everyone pinging

### *Proposed Solution*
Add a Announcements role and add a react in #readme for the role to be added to you (i'm pretty sure Dyno bot can do this? if not I can probably make a PR in the Cyberdisc bot to do this (if it has perms to add roles))

### *Additional Comments:*
N/A

### PR DESCRIPTION
**Pull request by thebeanogamer**
Resolves #280

### CODE REVIEW

**Comment by thebeanogamer** [comment]
Hex code suggestions plz.

**Comment by teamshortcut** [comment]
~Bring back yellow?~

**Comment by RealJammy** [comment]
Red.

**Review by SSAFuze — APPROVED** [review]

**Comment by thebeanogamer** [comment]
`!joinannouncements` and `!leaveannouncements` have been created.

**Pull request merged**
