### PR TITLE
Add a debate channel

### PR DESCRIPTION
**Pull request by fractalpenguin**
Have a channel for moderated debate, so that people can conduct rational debates with civility in mind.
Currently, the only channel appropriate for debate is `#overflow`, which frequently descends into chaos.

### CODE REVIEW

**Comment by SSAFuze** [comment]
To clarify, you want a channel specifically for debate in which moderators moderate it?

**Comment by fractalpenguin** [comment]
One where there are formalised rules of debate.

**Comment by Bottersnike** [comment]
I'd be happy to play a devils-advocate-for-hire ;)

**Comment by lightspeedana** [comment]
I feel like this is a bit vague at the moment, and other channels could host or conduct these debates, perhaps more topically? Also, who would run them?

**Comment by lightspeedana** [comment]
Inactive and haven't received feedback, so closing for now.

**Pull request closed without merging**
