### PR TITLE
Added Game Support

### PR DESCRIPTION
**Pull request by NicholasG04**
ignore loads of commits lmfao

### CODE REVIEW

**Comment by NicholasG04** [comment]
shit something went wrong in rebase one second

**Comment by NicholasG04** [comment]
ready @lightspeedana

**Comment by Bentechy66** [comment]
how do you fuck up git this badly

**Comment by NicholasG04** [comment]
Honestly, I can’t answer that



This is the worst pr I’ve ever done



Lmao kmn

**Comment by Bottersnike** [comment]
Dare I ask, how would who gets this role be decided? Just allowing people to arbitrarily apply it to themselves instantly devalues it as a role you can ping for good support, because suddenly everyone and their dog has it.

**Comment by NicholasG04** [comment]
mate, in my implementations of a similar 'tech support' system in other servers it works fine. no apply necessary, just reaction role. it's about people wanting to help ennit. you can always bar people from it - gucci imo. it ain't about the BEST people, there could be another system for that (like a mentor alternative but better) - it's about the people that wanna help blud

ygm?

**Comment by NicholasG04** [comment]
in my endz followin prev exampl we had de tech expert applications for the dons that really know how to turn on a computer ennit - dem the people u can well trust for dem real helps ennit

**Review by lightspeedana — APPROVED** [review]

**Pull request merged**
