### PR TITLE
Add License

### PR DESCRIPTION
**Pull request by thebeanogamer**
Adds a License file to the repository, using the MIT license like all the other repos on the org.

### CODE REVIEW

**Review by teamshortcut — APPROVED** [review]

**Comment by Bottersnike** [comment]
Not that this is bad as such, but _why_ add a LICENSE file? This isn't a code repo, likely never will hold code, and is just being used really as a discussion forum and using the repo to store decided fate. I can't think of any situation a LICENSE is actually going to be applicable except to silence the message from github prompting you to add one.

**Comment by NicholasG04** [comment]
I agree, totally and utterly useless in this instance.

**Comment by thebeanogamer** [comment]
_But then it looks nice and uniform with the other repos!_

**Comment by NicholasG04** [comment]
Disgusting that the server admins are acting in such an immature way about what are, in fact, very pressing issues to the prosperity of the server.

(/s)

**Comment by thebeanogamer** [comment]
HELP, I DON'T KNOW WHERE THE SARCASM STARTS AND THE SOMEWHAT POINTLESS PR ENDS!

**Comment by NicholasG04** [comment]
I mean personally I wish the sarcasm started at the creation of this utterly useless pull request...

**Comment by teamshortcut** [comment]
A license is hardly killing anybody; if nothing else, it enforces consistency within the organisation and as @Bottersnike said, suppresses an annoying notification.

**Comment by NicholasG04** [comment]
I mean if the license was used to cut someones throat.....

(I'm only joking).

It doesn't really hold that much of an effect so who really cares.

**Review by lightspeedana — APPROVED** [review]

**Pull request merged**
