### PR TITLE
Add #technology

### PR DESCRIPTION
**Pull request by Trefonix**
Added a new channel under 'Keyboard Warriors' as it seems fitting and in keeping with #media and #gaming.

### CODE REVIEW

**Review by teamshortcut — APPROVED** [review]
Happy for this to go to a vote in #meta 👍

**Review by thebeanogamer — APPROVED** [review]
While I'm not entirely convinced myself, I don't see a problem with bringing this to a vote.

**Comment by thebeanogamer** [comment]
Would #tech be better than #technology?

**Comment by teamshortcut** [comment]
I think #tech would be better; either way, I wont merge until voting has finished.

**Comment by thebeanogamer** [comment]
This:
image
vs this:
image

**Pull request merged**
