### PR TITLE
Add #deep

### PR DESCRIPTION
**Pull request by Bentechy66**
This channel has been highly requested by the community and, in my opinion, would be used.

### CODE REVIEW

**Comment by IlleQuiProgrammat** [comment]
Perhaps we could also add r/iam14andthisisdeep sub to it through mee6 or other?

**Comment by lightspeedana** [comment]
Right, I think this is a fairly clear suggestion, and since I don't need any clarity on it, I'll put it in #meta for voting 😄

**Comment by lightspeedana** [comment]
Sorry, another accidental closure! Will merge if upvoting is high.

**Comment by lightspeedana** [comment]
Closed due to split vote.

**Pull request closed without merging**
