### PR TITLE
Add "Almost 100%" role

### PR DESCRIPTION
**Pull request by 0cool-glitch**
The 100% role is a critical part of the server to understand who to ask for help. This role will help people understand they can ask for all help except volcano 5.6.

### CODE REVIEW

**Comment by Bentechy66** [comment]
When I was memeing about this I wasn't serious about it being added. Although that's not to say I'd *complain* if it was added...

**Comment by thebeanogamer** [comment]
Have you considered trying harder?

**Comment by Bentechy66** [comment]
> Have you considered trying harder?

To be fair, it's been several weeks now and still nobody has solved 5.6; I think this role should be added at least until someone does.

**Comment by thebeanogamer** [comment]
> 
> 
> > Have you considered trying harder?
> 
> To be fair, it's been several weeks now and still nobody has solved 5.6; I think this role should be added at least until someone does.

Sounds like you're not trying hard enough.

**Comment by Denrogh** [comment]
In my **### _personal view_** there is no need for a nearly 100% role. Yes 5.6 is arguably a rubbish challenge or maybe it is ingenious no one knows but a solution is out there like for all other CD challenges so this is no special case

**Comment by q-uu-rt** [comment]
two cents on this, commonly the 100% role was used to categorize and identify progress in the server and those who where at that point, as this was a general milestone. With Volcano, as it stands while its argued there are a few major milestones, it seems that the jump in complexity or, well, knowing what to do on the final stage can kind of warrant this on its own. As it stands the big divider right now would be those who have done 5.4, and those who haven't. Although as 5.5 is generally quite easy, putting the mark at getting onto 5.6 for this role would make sense, as no one on the server has managed to complete it yet. 

Overall, adding this role will generally allow us to more easily identify who has gotten over the 5.4 barrier so far and the amount of people working on the 5.6 one, which as it stands is an insane barrier to leap, with so far starting to reach a month+ of work on this single challenge from some people with no solution. Its really more for sake of transparency.

**Comment by thebeanogamer** [comment]
The test is failing because this PR was created before the automatic labelling stuff was setup. If this is merged, we'll override it.

**Review by Sh3llcod3 — COMMENTED** [review]
@thebeanogamer So is this a thing that will happen or no?

**Comment by Sh3llcod3** [comment]
I don't think this role has been accepted, so if there is a burning need for it, we can always reopen this or create another PR.

**Pull request closed without merging**
