### PR TITLE
Add Catagory Title

### LINKED ISSUE #19: Collapsable Group addition
For the current channels of #announcments #readme and #meta there is no way to hide these in a category. It would be beneficial to be able to collapse these into a group to save on space when they are rarely updated.

### PR DESCRIPTION
**Pull request by ghost**
Resolves #19

### CODE REVIEW

**Comment by teamshortcut** [comment]
What would the category name be? `README` perhaps?

**Comment by ghost** [comment]
Yeah, i hadnt come up with a title so its good to have ideas

**Comment by NicholasG04** [comment]
@teamshortcut or maybe IMPORTANT, or SERVER INFO

**Review by teamshortcut — APPROVED** [review]
The name can be changed later if needed.

**Review by NicholasG04 — APPROVED** [review]
lookin good

**Comment by ghost** [comment]
Server info or Important would be my preferences, only because README suggests you read it once and then forget about it in a sense where as the others infer referencing back more commonly.

**Review by thebeanogamer — APPROVED** [review]

**Pull request merged**
